# kubetpl:syntax:$
apiVersion: v1
kind: Namespace
metadata:
  name: $SERVICE-$TIER
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: $SERVICE-$TIER-deployment
  labels:
    service: $SERVICE
    tier: $TIER
  namespace: $SERVICE-$TIER
spec:
  selector:
    matchLabels:
      service: $SERVICE
      tier: $TIER
  replicas: 2
  template:
    metadata: 
      labels:
        service: $SERVICE
        tier: $TIER
    spec:
      containers:
      - name: $SERVICE-$TIER-container
        image: bookingcontainerregistryy.azurecr.io/$SERVICE-$TIER:$BuildId-$ENV
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: $SERVICE-$TIER-svc
  namespace: $SERVICE-$TIER
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  selector:
    service: $SERVICE
    tier: $TIER